# Generated by Django 5.2 on 2025-08-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير'), ('supervisor', 'مشرف'), ('moderator', 'مستخدم نظام')], default='moderator', max_length=10),
        ),
    ]
