# Generated by Django 5.2 on 2025-05-14 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_alter_employee_marital_status_alter_employee_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'يرجى إدخال اسم المشروع.', 'max_length': 'اسم المشروع طويل جدًا.'}, max_length=255, verbose_name='اسم المشروع')),
                ('status', models.CharField(choices=[('in-progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('pending-approval', 'قيد الموافقة'), ('paused', 'متوقف')], default='pending-approval', max_length=20, verbose_name='الحالة')),
                ('start_date', models.DateField(error_messages={'invalid': 'يرجى إدخال تاريخ صالح.'}, verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(error_messages={'invalid': 'يرجى إدخال تاريخ صالح.'}, verbose_name='تاريخ الانتهاء')),
                ('client', models.CharField(blank=True, max_length=100, null=True, verbose_name='العميل')),
                ('budget', models.DecimalField(decimal_places=2, error_messages={'invalid': 'يرجى إدخال رقم صحيح.'}, max_digits=12, verbose_name='الميزانية')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('assigned_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee', verbose_name='الفريق المسؤول')),
                ('team_members', models.ManyToManyField(blank=True, related_name='projects', to='employees.employee', verbose_name='أعضاء الفريق')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'blank': 'يرجى إدخال عنوان المهمة.', 'max_length': 'عنوان المهمة طويل جدًا.'}, max_length=255, verbose_name='عنوان المهمة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('department', models.CharField(max_length=100, verbose_name='القسم')),
                ('status', models.CharField(choices=[('completed', 'مكتمل'), ('incomplete', 'غير مكتمل'), ('overdue', 'متأخر')], default='incomplete', max_length=20, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'مرتفع')], default='low', max_length=20, verbose_name='الأولوية')),
                ('due_date', models.DateField(error_messages={'invalid': 'يرجى إدخال تاريخ صالح.'}, verbose_name='تاريخ الاستحقاق')),
                ('assigned_to', models.ManyToManyField(related_name='tasks', to='employees.employee', verbose_name='الموظف المكلّف')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'مهمة',
                'verbose_name_plural': 'المهام',
            },
        ),
    ]
