# Generated by Django 5.2 on 2025-05-15 12:06

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_department_options'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assigned_team',
        ),
        migrations.RemoveField(
            model_name='project',
            name='team_members',
        ),
        migrations.RemoveField(
            model_name='task',
            name='department',
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisors',
            field=models.ManyToManyField(blank=True, related_name='supervised_projects', to='employees.employee', verbose_name='المشرفون'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='task',
            name='departments',
            field=models.ManyToManyField(to='employees.department', verbose_name='الأقسام'),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in-progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('pending-approval', 'قيد الموافقة'), ('paused', 'متوقف'), ('overdue', 'متأخر')], db_index=True, default='pending-approval', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(related_name='tasks', to='employees.employee', verbose_name='الموظفين المكلّف'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(error_messages={'invalid': 'يرجى إدخال تاريخ صالح.'}, validators=[django.core.validators.MinValueValidator(datetime.date(2025, 5, 15))], verbose_name='تاريخ الاستحقاق'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'مرتفع')], db_index=True, default='low', max_length=20, verbose_name='الأولوية'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('completed', 'مكتمل'), ('incomplete', 'غير مكتمل'), ('overdue', 'متأخر')], db_index=True, default='incomplete', max_length=20, verbose_name='الحالة'),
        ),
    ]
