# Generated by Django 5.2 on 2025-05-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ongoing', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('pending-approval', 'قيد الموافقة'), ('paused', 'متوقف'), ('overdue', 'متأخر')], db_index=True, default='pending-approval', max_length=20, verbose_name='الحالة'),
        ),
    ]
