# Generated by Django 5.2 on 2025-05-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ongoing', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('pending-approval', 'قيد الموافقة'), ('paused', 'متوقف')], db_index=True, default='pending-approval', max_length=20, verbose_name='الحالة'),
        ),
    ]
