# Generated by Django 5.2 on 2025-05-18 11:32

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_updated_at_remove_task_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(error_messages={'invalid': 'يرجى إدخال تاريخ صالح.'}, validators=[django.core.validators.MinValueValidator(datetime.date(2025, 5, 18))], verbose_name='تاريخ الاستحقاق'),
        ),
    ]
