# Generated by Django 5.2 on 2025-05-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('completed', 'مكتمل'), ('incomplete', 'غير مكتمل')], db_index=True, default='incomplete', max_length=20, verbose_name='الحالة'),
        ),
    ]
