# Generated by Django 5.2 on 2025-05-21 09:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(error_messages={'invalid': 'يرجى إدخال تاريخ صالح.'}, validators=[django.core.validators.MinValueValidator(datetime.date(2025, 5, 21))], verbose_name='تاريخ الاستحقاق'),
        ),
    ]
