# Generated by Django 5.2 on 2025-05-23 21:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress_start_date',
            field=models.DateField(blank=True, error_messages={'invalid': 'يرجى إدخال تاريخ صالح.'}, null=True, verbose_name='تاريخ بدء التنفيذ'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, error_messages={'invalid': 'يرجى إدخال تاريخ صالح.'}, null=True, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(error_messages={'invalid': 'يرجى إدخال تاريخ صالح.'}, validators=[django.core.validators.MinValueValidator(datetime.date(2025, 5, 24))], verbose_name='تاريخ الاستحقاق'),
        ),
    ]
