# Generated by Django 5.2 on 2025-05-23 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_progress_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='progress_start_date',
            new_name='progress_started',
        ),
    ]
