# Generated by Django 5.2 on 2025-07-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(error_messages={'blank': 'يرجى إدخال رقم الموظف.', 'null': 'رقم الموظف لا يمكن أن يكون فارغًا.', 'unique': 'رقم الموظف مستخدم من قبل.'}, max_length=20, unique=True, verbose_name='رقم الموظف')),
                ('name', models.CharField(error_messages={'blank': 'يرجى إدخال الاسم الكامل.', 'null': 'الاسم الكامل لا يمكن أن يكون فارغًا.'}, max_length=100, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(error_messages={'blank': 'يرجى إدخال رقم الجوال.', 'null': 'رقم الجوال لا يمكن أن يكون فارغًا.'}, max_length=15, verbose_name='رقم الجوال')),
                ('national_id', models.CharField(error_messages={'blank': 'يرجى إدخال رقم الهوية.', 'null': 'رقم الهوية لا يمكن أن يكون فارغًا.', 'unique': 'رقم الهوية مستخدم من قبل.'}, max_length=20, unique=True, verbose_name='رقم الهوية')),
                ('email', models.EmailField(blank=True, error_messages={'invalid': 'يرجى إدخال بريد إلكتروني صالح.'}, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='المسمى الوظيفي')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفون',
            },
        ),
        migrations.CreateModel(
            name='SecurityGuard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'حارس أمن',
                'verbose_name_plural': 'حراس الأمن',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('الوردية الأولى', 'الوردية الأولى'), ('الوردية الثانية', 'الوردية الثانية'), ('الوردية الثالثة', 'الوردية الثالثة')], max_length=20, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
