# Generated by Django 5.0.6 on 2025-05-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mode',
            field=models.CharField(choices=[('remote', 'عن بُعد'), ('on-site', 'من المقر'), ('hybrid', 'هجين')], max_length=100),
        ),
    ]
