# Generated by Django 5.2 on 2025-07-31 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أُضيف بواسطة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='الحساب المرتبط'),
        ),
        migrations.AddField(
            model_name='securityguard',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.shift', verbose_name='الوردية'),
        ),
    ]
