# Generated by Django 5.2 on 2025-07-31 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='start_time',
        ),
    ]
