# Generated by Django 5.2 on 2025-05-12 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'الموظف', 'verbose_name_plural': 'الموظفين'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=100, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='العمر'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أُضيف بواسطة'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='employees/cv', verbose_name='السيرة الذاتية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.department', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(error_messages={'unique': 'هذا البريد الإلكتروني مستخدم من قبل.'}, max_length=100, unique=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(error_messages={'unique': 'رقم الموظف مستخدم من قبل.'}, max_length=10, unique=True, verbose_name='رقم الموظف'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=6, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التعيين'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='employees/images', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(choices=[('single', 'أعزب'), ('married', 'متزوج')], max_length=8, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mode',
            field=models.CharField(choices=[('remote', 'عن بُعد'), ('on-site', 'من المقر'), ('hybrid', 'هجين')], max_length=100, verbose_name='نمط العمل'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='national_id',
            field=models.CharField(error_messages={'unique': 'الرقم القومي مستخدم من قبل.'}, max_length=100, unique=True, verbose_name='الرقم القومي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(error_messages={'unique': 'رقم الهاتف مستخدم من قبل.'}, max_length=20, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=100, verbose_name='الوظيفة'),
        ),
    ]
