# Generated by Django 5.2 on 2025-07-31 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_shift_end_time_remove_shift_start_time'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityguard',
            name='locations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.location', verbose_name='الموقع'),
        ),
    ]
