# Generated by Django 5.2 on 2025-05-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_options_alter_employee_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(choices=[('single', 'أعزب'), ('married', 'متزوج'), ('divorced', 'مطلق'), ('widowed', 'أرمل')], max_length=8, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mode',
            field=models.CharField(choices=[('remote', 'عن بُعد'), ('on-site', 'من المقر'), ('hybrid', 'هجين')], max_length=100, verbose_name='وضع العمل'),
        ),
    ]
