# Generated by Django 5.2 on 2025-07-31 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_securityguard_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securityguard',
            old_name='locations',
            new_name='location',
        ),
    ]
