# Generated by Django 5.2 on 2025-05-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_marital_status_alter_employee_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'القسم', 'verbose_name_plural': 'الأقسام'},
        ),
    ]
