# Generated by Django 5.2 on 2025-08-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_rename_locations_securityguard_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityguard',
            name='employee_id',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='الرقم الوظيفي'),
            preserve_default=False,
        ),
    ]
