# Generated by Django 5.2 on 2025-08-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_securityguard_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityguard',
            name='shift',
        ),
        migrations.AddField(
            model_name='securityguard',
            name='shift',
            field=models.ManyToManyField(related_name='security_guards', to='employees.shift', verbose_name='الورديات'),
        ),
    ]
