# Generated by Django 5.2 on 2025-08-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_securityguard_shift_securityguard_shift'),
        ('projects', '0002_alter_location_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securityguard',
            old_name='shift',
            new_name='shifts',
        ),
        migrations.RemoveField(
            model_name='securityguard',
            name='location',
        ),
        migrations.AddField(
            model_name='securityguard',
            name='locations',
            field=models.ManyToManyField(related_name='security_guards', to='projects.location', verbose_name='الموقع'),
        ),
    ]
