# Generated by Django 5.2 on 2025-07-27 11:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_delete_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'موظف', 'verbose_name_plural': 'الموظفون'},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='birth_date',
            new_name='birthdate',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mode',
        ),
        migrations.AddField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الانضمام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='الحساب المرتبط'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, error_messages={'invalid': 'يرجى إدخال بريد إلكتروني صالح.'}, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(error_messages={'blank': 'يرجى إدخال رقم الموظف.', 'null': 'رقم الموظف لا يمكن أن يكون فارغًا.', 'unique': 'رقم الموظف مستخدم من قبل.'}, max_length=20, unique=True, verbose_name='رقم الموظف'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(error_messages={'blank': 'يرجى إدخال الاسم الكامل.', 'null': 'الاسم الكامل لا يمكن أن يكون فارغًا.'}, max_length=100, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='national_id',
            field=models.CharField(error_messages={'blank': 'يرجى إدخال رقم الهوية.', 'null': 'رقم الهوية لا يمكن أن يكون فارغًا.', 'unique': 'رقم الهوية مستخدم من قبل.'}, max_length=20, unique=True, verbose_name='رقم الهوية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(error_messages={'blank': 'يرجى إدخال رقم الجوال.', 'null': 'رقم الجوال لا يمكن أن يكون فارغًا.'}, max_length=15, verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المسمى الوظيفي'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
