# Generated by Django 5.2 on 2025-08-23 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_rename_shift_securityguard_shifts_and_more'),
        ('projects', '0002_alter_location_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityguard',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='securityguard',
            name='shifts',
        ),
        migrations.AddField(
            model_name='securityguard',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SecurityGuardLocationShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_shifts', to='employees.securityguard')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guard_shifts', to='projects.location')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guard_locations', to='employees.shift')),
            ],
            options={
                'verbose_name': 'وردية الحارس في الموقع',
                'verbose_name_plural': 'ورديات الحراس في المواقع',
            },
        ),
    ]
