# Generated by Django 5.2 on 2025-07-30 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_remove_employee_department_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('الوردية الأولى', 'الوردية الأولى'), ('الوردية الثانية', 'الوردية الثانية'), ('الوردية الثالثة', 'الوردية الثالثة')], max_length=20, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SecurityGuard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.shift', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'حارس أمن',
                'verbose_name_plural': 'حراس الأمن',
            },
        ),
    ]
