# Generated by Django 5.2 on 2025-08-28 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_remove_securityguard_locations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securityguardlocationshift',
            options={'verbose_name': 'وردية في موقع', 'verbose_name_plural': 'ورديات المواقع'},
        ),
    ]
