# Generated by Django 5.2 on 2025-09-26 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_securityguardlocationshift_options'),
        ('projects', '0002_alter_location_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='securityguardlocationshift',
            unique_together={('guard', 'location', 'shift')},
        ),
    ]
