# Generated by Django 5.2 on 2025-09-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_securityguardlocationshift_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityguard',
            name='employee_id',
            field=models.IntegerField(unique=True, verbose_name='الرقم الوظيفي'),
        ),
    ]
