# Generated by Django 5.2 on 2025-07-31 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ الزيارة')),
                ('time', models.TimeField(verbose_name='وقت الزيارة')),
                ('purpose', models.TextField(help_text='صف الهدف من الزيارة', verbose_name='الهدف من الزيارة')),
                ('status', models.CharField(choices=[('مجدولة', 'مجدولة'), ('مكتملة', 'مكتملة')], default='مجدولة', max_length=20, verbose_name='حالة الزيارة')),
                ('completed_at', models.DateTimeField(blank=True, help_text='تاريخ ووقت اكتمال تقرير الزيارة', null=True, verbose_name='تاريخ استكمال التقرير')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='employees.employee', verbose_name='الموظف المسؤول')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='projects.location', verbose_name='الموقع')),
            ],
            options={
                'verbose_name': 'زيارة',
                'verbose_name_plural': 'الزيارات',
                'unique_together': {('location', 'employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('تأخير عن الدوام', 'تأخير عن الدوام'), ('التدخين بالموقع أثناء العمل', 'التدخين بالموقع أثناء العمل'), ('عدم الالتزام بالزي الرسمي', 'عدم الالتزام بالزي الرسمي'), ('غياب', 'غياب'), ('ترك الموقع (انسحاب)', 'ترك الموقع (انسحاب)'), ('التجمع في منطقة العمل', 'التجمع في منطقة العمل'), ('الشكوى من العميل', 'الشكوى من العميل'), ('عدم احترام الرئيس المباشر', 'عدم احترام الرئيس المباشر'), ('استخدام الجوال أثناء العمل', 'استخدام الجوال أثناء العمل'), ('أخرى', 'أخرى')], max_length=50, verbose_name='نوع المخالفة')),
                ('severity', models.CharField(choices=[('منخفضة', 'منخفضة'), ('متوسطة', 'متوسطة'), ('عالية', 'عالية')], max_length=10, verbose_name='درجة الخطورة')),
                ('details', models.TextField(help_text='يرجى كتابة تفاصيل المخالفة', verbose_name='وصف تفصيلي للمخالفة')),
                ('supervisor_explanation', models.TextField(blank=True, verbose_name='شرح البيان من المشرف')),
                ('violation_image', models.ImageField(blank=True, null=True, upload_to='violations/', verbose_name='تصوير فوري للمخالفة')),
                ('action', models.TextField(blank=True, verbose_name='الإجراء')),
                ('guidance', models.TextField(blank=True, verbose_name='التوجيه')),
                ('penalty', models.TextField(blank=True, verbose_name='الجزاء المطبق للائحة')),
                ('confirmed_by_ops', models.BooleanField(default=False, verbose_name='التأكيد من مدير العمليات')),
                ('confirmed_by_monitoring', models.BooleanField(default=False, verbose_name='التأكيد من قسم المتابعة والحفظ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='violation', to='visits.visit', verbose_name='الزيارة')),
            ],
            options={
                'verbose_name': 'مخالفة',
                'verbose_name_plural': 'المخالفات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guard_presence', models.CharField(choices=[('جيد', 'جيد'), ('يحتاج إلى معالجة', 'يحتاج إلى معالجة')], max_length=20, verbose_name='تواجد الحارس في موقعه')),
                ('uniform_cleanliness', models.CharField(choices=[('جيد', 'جيد'), ('يحتاج إلى معالجة', 'يحتاج إلى معالجة')], max_length=20, verbose_name='نظافة الزي الرسمي')),
                ('attendance_records', models.CharField(choices=[('جيد', 'جيد'), ('يحتاج إلى معالجة', 'يحتاج إلى معالجة')], max_length=20, verbose_name='سجلات الحضور والانصراف والسجلات الخاصة بالموقع')),
                ('shift_handover', models.CharField(choices=[('جيد', 'جيد'), ('يحتاج إلى معالجة', 'يحتاج إلى معالجة')], max_length=20, verbose_name='الانضباط في تسليم واستلام الورديات')),
                ('lighting', models.CharField(choices=[('جيد', 'جيد'), ('يحتاج إلى معالجة', 'يحتاج إلى معالجة')], max_length=20, verbose_name='الإضاءة حول محيط الموقع')),
                ('cameras', models.CharField(choices=[('جيد', 'جيد'), ('يحتاج إلى معالجة', 'يحتاج إلى معالجة')], max_length=20, verbose_name='كاميرات المراقبة')),
                ('security_vehicles', models.CharField(choices=[('جيد', 'جيد'), ('يحتاج إلى معالجة', 'يحتاج إلى معالجة')], max_length=20, verbose_name='السيارات الأمنية')),
                ('radio_devices', models.CharField(choices=[('جيد', 'جيد'), ('يحتاج إلى معالجة', 'يحتاج إلى معالجة')], max_length=20, verbose_name='عمل أجهزة الاتصال اللاسلكي')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توجيهات أو توصيات من العميل')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='visit_reports/', verbose_name='مرفقات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='visits.visit', verbose_name='الزيارة')),
            ],
            options={
                'verbose_name': 'تقرير الزيارة',
                'verbose_name_plural': 'تقارير الزيارات',
            },
        ),
    ]
