# Generated by Django 5.2 on 2025-07-27 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0009_remove_employee_department_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='أدخل اسم المشروع', max_length=255, verbose_name='اسم المشروع')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='أدخل اسم الموقع', max_length=255, verbose_name='اسم الموقع')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='visits.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'موقع',
                'verbose_name_plural': 'المواقع',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ الزيارة')),
                ('time', models.TimeField(verbose_name='وقت الزيارة')),
                ('purpose', models.TextField(help_text='صف الهدف من الزيارة', verbose_name='الهدف من الزيارة')),
                ('visit_status', models.CharField(choices=[('scheduled', 'مجدولة'), ('completed', 'مكتملة')], default='scheduled', max_length=20, verbose_name='حالة الزيارة')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='employees.employee', verbose_name='الموظف المسؤول')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='visits.location', verbose_name='الموقع')),
            ],
            options={
                'verbose_name': 'زيارة',
                'verbose_name_plural': 'الزيارات',
            },
        ),
    ]
