# Generated by Django 5.2 on 2025-08-05 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_rename_locations_securityguard_location'),
        ('projects', '0001_initial'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitreport',
            old_name='notes',
            new_name='client_notes',
        ),
        migrations.RemoveField(
            model_name='violation',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='visitreport',
            name='attachment',
        ),
        migrations.AddField(
            model_name='violation',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='violation',
            name='location',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='violation', to='projects.location', verbose_name='الموقع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitreport',
            name='attendance_records_attachment',
            field=models.FileField(blank=True, null=True, upload_to='visit_reports/', verbose_name='مرفق السجلات'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='attendance_records_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظة السجلات'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='cameras_attachment',
            field=models.FileField(blank=True, null=True, upload_to='visit_reports/', verbose_name='مرفق الكاميرات'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='cameras_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظة الكاميرات'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='guard_presence_attachment',
            field=models.FileField(blank=True, null=True, upload_to='visit_reports/', verbose_name='مرفق تواجد الحارس'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='guard_presence_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظة تواجد الحارس'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='lighting_attachment',
            field=models.FileField(blank=True, null=True, upload_to='visit_reports/', verbose_name='مرفق الإضاءة'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='lighting_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظة الإضاءة'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='radio_devices_attachment',
            field=models.FileField(blank=True, null=True, upload_to='visit_reports/', verbose_name='مرفق الأجهزة اللاسلكية'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='radio_devices_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظة الأجهزة اللاسلكية'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='security_vehicles_attachment',
            field=models.FileField(blank=True, null=True, upload_to='visit_reports/', verbose_name='مرفق السيارات الأمنية'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='security_vehicles_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظة السيارات الأمنية'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='shift_handover_attachment',
            field=models.FileField(blank=True, null=True, upload_to='visit_reports/', verbose_name='مرفق الورديات'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='shift_handover_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظة الورديات'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='supervisor_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات المشرف'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='uniform_cleanliness_attachment',
            field=models.FileField(blank=True, null=True, upload_to='visit_reports/', verbose_name='مرفق نظافة الزي'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='uniform_cleanliness_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظة نظافة الزي'),
        ),
    ]
