# Generated by Django 5.2 on 2025-07-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='visit_status',
            new_name='status',
        ),
    ]
