# Generated by Django 5.2 on 2025-08-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_rename_notes_visitreport_client_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitreport',
            name='other',
            field=models.CharField(choices=[('جيد', 'جيد'), ('يحتاج إلى معالجة', 'يحتاج إلى معالجة')], default=1, max_length=20, verbose_name='أخرى'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitreport',
            name='other_attachment',
            field=models.FileField(blank=True, null=True, upload_to='visit_reports/', verbose_name='مرفق أخرى'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='other_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظة أخرى'),
        ),
    ]
