# Generated by Django 5.2 on 2025-07-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_remove_employee_department_alter_employee_options_and_more'),
        ('visits', '0002_rename_visit_status_visit_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visit',
            unique_together={('location', 'employee', 'date')},
        ),
    ]
