# Generated by Django 5.2 on 2025-08-05 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_visitreport_other_visitreport_other_attachment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['date', 'time'], 'verbose_name': 'زيارة', 'verbose_name_plural': 'الزيارات'},
        ),
    ]
