# Generated by Django 5.2 on 2025-07-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_alter_visit_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ ووقت اكتمال تقرير الزيارة', null=True, verbose_name='تاريخ استكمال التقرير'),
        ),
    ]
