# Generated by Django 5.2 on 2025-08-06 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_securityguard_employee_id'),
        ('visits', '0004_alter_visit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='security_guard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='violation', to='employees.securityguard', verbose_name='الموظف المخالف'),
            preserve_default=False,
        ),
    ]
