# Generated by Django 5.2 on 2025-07-28 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_visit_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('مجدولة', 'مجدولة'), ('مكتملة', 'مكتملة')], default='مجدولة', max_length=20, verbose_name='حالة الزيارة'),
        ),
        migrations.CreateModel(
            name='VisitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guard_presence', models.CharField(choices=[('جيد', 'جيد'), ('يحتاج إلى معالجة', 'يحتاج إلى معالجة')], max_length=20, verbose_name='تواجد الحارس في موقعه')),
                ('uniform_cleanliness', models.CharField(choices=[('جيد', 'جيد'), ('يحتاج إلى معالجة', 'يحتاج إلى معالجة')], max_length=20, verbose_name='نظافة الزي الرسمي')),
                ('attendance_records', models.CharField(choices=[('جيد', 'جيد'), ('يحتاج إلى معالجة', 'يحتاج إلى معالجة')], max_length=20, verbose_name='سجلات الحضور والانصراف والسجلات الخاصة بالموقع')),
                ('shift_handover', models.CharField(choices=[('جيد', 'جيد'), ('يحتاج إلى معالجة', 'يحتاج إلى معالجة')], max_length=20, verbose_name='الانضباط في تسليم واستلام الورديات')),
                ('lighting', models.CharField(choices=[('جيد', 'جيد'), ('يحتاج إلى معالجة', 'يحتاج إلى معالجة')], max_length=20, verbose_name='الإضاءة حول محيط الموقع')),
                ('cameras', models.CharField(choices=[('جيد', 'جيد'), ('يحتاج إلى معالجة', 'يحتاج إلى معالجة')], max_length=20, verbose_name='كاميرات المراقبة')),
                ('security_vehicles', models.CharField(choices=[('جيد', 'جيد'), ('يحتاج إلى معالجة', 'يحتاج إلى معالجة')], max_length=20, verbose_name='السيارات الأمنية')),
                ('radio_devices', models.CharField(choices=[('جيد', 'جيد'), ('يحتاج إلى معالجة', 'يحتاج إلى معالجة')], max_length=20, verbose_name='عمل أجهزة الاتصال اللاسلكي')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توجيهات أو توصيات من العميل')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='visit_reports/', verbose_name='مرفقات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='visits.visit', verbose_name='الزيارة')),
            ],
            options={
                'verbose_name': 'تقرير الزيارة',
                'verbose_name_plural': 'تقارير الزيارات',
            },
        ),
    ]
