# Generated by Django 5.2 on 2025-07-29 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_alter_visit_status_visitreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitreport',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('تأخير عن الدوام', 'تأخير عن الدوام'), ('التدخين بالموقع أثناء العمل', 'التدخين بالموقع أثناء العمل'), ('عدم الالتزام بالزي الرسمي', 'عدم الالتزام بالزي الرسمي'), ('غياب', 'غياب'), ('ترك الموقع (انسحاب)', 'ترك الموقع (انسحاب)'), ('التجمع في منطقة العمل', 'التجمع في منطقة العمل'), ('الشكوى من العميل', 'الشكوى من العميل'), ('عدم احترام الرئيس المباشر', 'عدم احترام الرئيس المباشر'), ('استخدام الجوال أثناء العمل', 'استخدام الجوال أثناء العمل'), ('أخرى', 'أخرى')], max_length=50, verbose_name='نوع المخالفة')),
                ('severity', models.CharField(choices=[('منخفضة', 'منخفضة'), ('متوسطة', 'متوسطة'), ('عالية', 'عالية')], max_length=10, verbose_name='درجة الخطورة')),
                ('details', models.TextField(help_text='يرجى كتابة تفاصيل المخالفة', verbose_name='وصف تفصيلي للمخالفة')),
                ('supervisor_explanation', models.TextField(blank=True, verbose_name='شرح البيان من المشرف')),
                ('violation_image', models.ImageField(blank=True, null=True, upload_to='violations/', verbose_name='تصوير فوري للمخالفة')),
                ('action', models.TextField(blank=True, verbose_name='الإجراء')),
                ('guidance', models.TextField(blank=True, verbose_name='التوجيه')),
                ('penalty', models.TextField(blank=True, verbose_name='الجزاء المطبق للائحة')),
                ('confirmed_by_ops', models.BooleanField(default=False, verbose_name='التأكيد من مدير العمليات')),
                ('confirmed_by_monitoring', models.BooleanField(default=False, verbose_name='التأكيد من قسم المتابعة والحفظ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='violation', to='visits.visit', verbose_name='الزيارة')),
            ],
            options={
                'verbose_name': 'مخالفة',
                'verbose_name_plural': 'المخالفات',
                'ordering': ['-created_at'],
            },
        ),
    ]
