# Generated by Django 5.2 on 2025-08-06 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_location_unique_together'),
        ('visits', '0005_violation_security_guard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation', to='projects.location', verbose_name='الموقع'),
        ),
    ]
