# Generated by Django 5.2 on 2025-08-29 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_securityguardlocationshift_options'),
        ('projects', '0002_alter_location_unique_together'),
        ('visits', '0006_alter_violation_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visit',
            unique_together={('location', 'employee', 'date', 'time')},
        ),
    ]
