# Generated by Django 5.2 on 2025-09-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0007_alter_visit_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ المخالفة'),
        ),
    ]
