# Generated by Django 5.2 on 2025-09-03 15:32

from django.db import migrations
from django.conf import settings


def populate_date(apps, schema_editor):
    Violation = apps.get_model("visits", "Violation")
    for v in Violation.objects.all():
        if not v.date:
            v.date = v.created_at.astimezone(settings.SAUDI_TZ).date()
            v.save(update_fields=["date"])


class Migration(migrations.Migration):
    dependencies = [
        ('visits', '0008_violation_date'),
    ]

    operations = [
        migrations.RunPython(populate_date),
    ]
