# Generated by Django 5.2 on 2025-09-04 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0009_auto_20250903_1832'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visit',
            unique_together=set(),
        ),
    ]
