# Generated by Django 5.2 on 2025-09-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0010_alter_visit_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitreport',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='إحداثيات خط العرض للمشرف'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='location_accuracy',
            field=models.FloatField(blank=True, null=True, verbose_name='دقة تحديد الموقع (بالمتر)'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='إحداثيات خط الطول للمشرف'),
        ),
    ]
