# Generated by Django 5.2 on 2025-10-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0011_visitreport_latitude_visitreport_location_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitreport',
            name='attendance_records',
            field=models.CharField(choices=[('جيد', 'جيد'), ('يحتاج إلى معالجة', 'يحتاج إلى معالجة'), ('غير متوفر', 'غير متوفر')], max_length=20, verbose_name='سجلات الحضور والانصراف والسجلات الخاصة بالموقع'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='cameras',
            field=models.CharField(choices=[('جيد', 'جيد'), ('يحتاج إلى معالجة', 'يحتاج إلى معالجة'), ('غير متوفر', 'غير متوفر')], max_length=20, verbose_name='كاميرات المراقبة'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='guard_presence',
            field=models.CharField(choices=[('جيد', 'جيد'), ('يحتاج إلى معالجة', 'يحتاج إلى معالجة'), ('غير متوفر', 'غير متوفر')], max_length=20, verbose_name='تواجد الحارس في موقعه'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='lighting',
            field=models.CharField(choices=[('جيد', 'جيد'), ('يحتاج إلى معالجة', 'يحتاج إلى معالجة'), ('غير متوفر', 'غير متوفر')], max_length=20, verbose_name='الإضاءة حول محيط الموقع'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='other',
            field=models.CharField(choices=[('جيد', 'جيد'), ('يحتاج إلى معالجة', 'يحتاج إلى معالجة'), ('غير متوفر', 'غير متوفر')], max_length=20, verbose_name='أخرى'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='radio_devices',
            field=models.CharField(choices=[('جيد', 'جيد'), ('يحتاج إلى معالجة', 'يحتاج إلى معالجة'), ('غير متوفر', 'غير متوفر')], max_length=20, verbose_name='عمل أجهزة الاتصال اللاسلكي'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='security_vehicles',
            field=models.CharField(choices=[('جيد', 'جيد'), ('يحتاج إلى معالجة', 'يحتاج إلى معالجة'), ('غير متوفر', 'غير متوفر')], max_length=20, verbose_name='السيارات الأمنية'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='shift_handover',
            field=models.CharField(choices=[('جيد', 'جيد'), ('يحتاج إلى معالجة', 'يحتاج إلى معالجة'), ('غير متوفر', 'غير متوفر')], max_length=20, verbose_name='الانضباط في تسليم واستلام الورديات'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='uniform_cleanliness',
            field=models.CharField(choices=[('جيد', 'جيد'), ('يحتاج إلى معالجة', 'يحتاج إلى معالجة'), ('غير متوفر', 'غير متوفر')], max_length=20, verbose_name='نظافة الزي الرسمي'),
        ),
    ]
