# Generated by Django 5.2 on 2025-10-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0012_alter_visitreport_attendance_records_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت المخالفة'),
        ),
    ]
