# Generated by Django 5.2 on 2025-10-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0013_violation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='اخر تعديل'),
        ),
    ]
