# Generated by Django 5.2 on 2025-10-16 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_employee_image'),
        ('visits', '0014_violation_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violation',
            name='confirmed_by_ops',
        ),
        migrations.AlterField(
            model_name='violation',
            name='security_guard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='violation', to='employees.securityguard', verbose_name='الموظف المخالف'),
        ),
    ]
