# Generated by Django 5.2 on 2025-07-30 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0010_shift_securityguard'),
        ('visits', '0006_remove_visitreport_updated_at_violation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ الوردية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='visits.location', verbose_name='الموقع')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.shift', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'حضور وردية',
                'verbose_name_plural': 'حضور الورديات',
                'unique_together': {('location', 'shift', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SecurityGuardAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('حاضر', 'حاضر'), ('متأخر', 'متأخر'), ('غائب', 'غائب')], max_length=10, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('security_guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.securityguard', verbose_name='حارس الأمن')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendances', to='attendance.shiftattendance', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'تسجيل حضور',
                'verbose_name_plural': 'تسجيلات الحضور',
                'unique_together': {('security_guard', 'shift')},
            },
        ),
    ]
