# Generated by Django 5.2 on 2025-07-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityGuardAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('حاضر', 'حاضر'), ('متأخر', 'متأخر'), ('غائب', 'غائب')], max_length=10, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'تسجيل حضور',
                'verbose_name_plural': 'تسجيلات الحضور',
            },
        ),
        migrations.CreateModel(
            name='ShiftAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ الوردية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'حضور وردية',
                'verbose_name_plural': 'حضور الورديات',
            },
        ),
    ]
