# Generated by Django 5.2 on 2025-07-31 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityguardattendance',
            name='security_guard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.securityguard', verbose_name='حارس الأمن'),
        ),
        migrations.AddField(
            model_name='shiftattendance',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='projects.location', verbose_name='الموقع'),
        ),
        migrations.AddField(
            model_name='shiftattendance',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.shift', verbose_name='الوردية'),
        ),
        migrations.AddField(
            model_name='securityguardattendance',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendances', to='attendance.shiftattendance', verbose_name='الوردية'),
        ),
        migrations.AlterUniqueTogether(
            name='shiftattendance',
            unique_together={('location', 'shift', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='securityguardattendance',
            unique_together={('security_guard', 'shift')},
        ),
    ]
