# Generated by Django 5.2 on 2025-06-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('saturday', 'السبت'), ('sunday', 'الأحد'), ('monday', 'الاثنين'), ('tuesday', 'الثلاثاء'), ('wednesday', 'الأربعاء'), ('thursday', 'الخميس'), ('friday', 'الجمعة')], max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'اليوم',
                'verbose_name_plural': 'الأيام',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم')),
                ('check_in', models.TimeField(verbose_name='وقت الحضور')),
                ('check_out', models.TimeField(verbose_name='وقت الانصراف')),
                ('grace_period', models.PositiveIntegerField(default=15, verbose_name='فترة السماحية')),
                ('working_days', models.ManyToManyField(to='attendance.day', verbose_name='أيام العمل')),
            ],
            options={
                'verbose_name': 'إعدادات الحضور',
                'verbose_name_plural': 'إعدادات الحضور',
            },
        ),
    ]
