# Generated by Django 5.2 on 2025-07-31 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('employees', '0005_rename_locations_securityguard_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='securityguardattendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shiftattendance',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
            preserve_default=False,
        ),
    ]
