# Generated by Django 5.2 on 2025-07-31 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_securityguardattendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityguardattendance',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guards', to='attendance.shiftattendance', verbose_name='الوردية'),
        ),
    ]
