# Generated by Django 5.2 on 2025-08-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_securityguardattendance_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityguardattendance',
            name='status',
            field=models.CharField(choices=[('حاضر', 'حاضر'), ('متأخر', 'متأخر'), ('غائب', 'غائب'), ('راحة', 'راحة')], max_length=10, verbose_name='الحالة'),
        ),
    ]
